### ISSUE TITLE
syntax of the command-node commands

### ISSUE THREAD

**Issue by nikolauzi11** [MintyTrebor/moonNode#10]
Hi,

I have only one question, but I do not know where else to ask it.
I am interested in the syntax of the command-node commands.
For example, what exactly must the command look like to shut down the host("machine.shutdown")?
I haven't found any further documentation or examples, unfortunately.

Thanks

**Comment by MintyTrebor** [comment]
It should accept any standard gcode/klipper command you can enter in the std klipper console
https://github.com/MintyTrebor/moonNode/wiki/moonNode-Command

**Comment by nikolauzi11** [comment]
Thank you very much, that helps already.
