### ISSUE TITLE
Using moonNode with the Docker version of Node-RED

### ISSUE THREAD

**Issue by fluxor99232** [MintyTrebor/moonNode#11]
Is there any chance of using this node with the Docker version of Node-RED (nodered/node-red:latest)? Install seems to fail due to the image apparently running on Node.js 16 instead of the 18 required by moonNode.

**Comment by MintyTrebor** [comment]
The node.js version was set using the node-red node.js recommended version at the time of publishing. You can choose the node.js version you want to use in docker by setting the appropriate tag when creating the docker:
https://hub.docker.com/r/nodered/node-red/tags

**Comment by fluxor99232** [comment]
Thank you! Setting it to "latest-18" worked flawlessly.

**Comment by AndreKR** [comment]
I have the same issue, running `3.1-debian`. I need Debian instead of Alpine because I use libraries that need compiling. I don't think there is an image that has 18 *and* Debian. Does MoonNode really need 18 or could it make do with 16?

**Comment by MintyTrebor** [comment]
It probably will run on 16, but I have not tested it. The nodejs version control is set in the package.json file, so you may be able to download the files manually, change the required nodejs version in the pagage.json and install it manually, but I do not how you would go about that in a docker container.
It seems strange that they are not using 18 as standard when their own documentation recommends it:  
https://nodered.org/docs/faq/node-versions
Might be worth rasing with the docker maintainers?

**Comment by AndreKR** [comment]
> It seems strange that they are not using 18 as standard when their own documentation recommends it:
https://nodered.org/docs/faq/node-versions
Might be worth rasing with the docker maintainers?

They're taking things slowly.
https://github.com/node-red/node-red-docker/issues/392
