### ISSUE TITLE
fullModel.toolhead.position array is growing

### ISSUE THREAD

**Issue by adjustinthings** [MintyTrebor/moonNode#12]
I don't know where this is originating but I'm running moonNode and Mainsail. 
When I jog the toolhead around on the dashboard of mainsail, the fullmodelposition array grows. 
![image](https://github.com/MintyTrebor/moonNode/assets/37949962/2e17227f-fefc-4947-ab16-06eb0caa2ce1)
![image](https://github.com/MintyTrebor/moonNode/assets/37949962/2be163f4-995a-4bee-8888-75cc2763503a)
![image](https://github.com/MintyTrebor/moonNode/assets/37949962/e5fb6283-5f5c-421f-931d-fc544670cc35)

Doesn't do it for the patchModel. That one is fine.

**Comment by MintyTrebor** [comment]
I can see how this is happening, and it consistent with the standard behaviour for most key/values eg: patchModel only contains the delta values.
I am wondering if the system is categorising all moves within a set time period as a single sequence of moves and only resets the full array after a pre-determined idle time. I will need to look at the raw data before processing to get an accurate picture.

**Comment by MintyTrebor** [comment]
I have just published 0.1.7 which changes the behaviour for the processing of toolhead.position data to always replace previous values, and not add new data to the existing array. Updated version should be available in the palette manager within 24hrs.
