### ISSUE TITLE
Macros and Filament Sensor

### ISSUE THREAD

**Issue by jonferreira** [MintyTrebor/moonNode#2]
Hey there.

I'm trying to figure out how I can use this to read the filament_switch_sensor and gcode_macro object -https://moonraker.readthedocs.io/en/latest/printer_objects/#gcode_macro-macro_name

Maybe it's just me being daff but couldn't find an object within node-red that holds those values?

Thanks

**Comment by MintyTrebor** [comment]
Hi,
filament_switch_sensor is not in the list of objects to select - I will add it for you (its not something I use so it is not reported as part of the object list when I query moonraker). I will have to make the change blind as I do not have a sensor. When I make the change I will update this thread with a version for you to test. I cannot give you an ETA, but it will be a few days...

Macro's can be called/run by using the moonNode CMD node. Macro's should just run like normal gcode commands.

In the meantime you can just use a normal http request node to get the current status of the sensor: Below is an example (just change the IP to yours).

`[{"id":"a3246b03.167648","type":"inject","z":"615b3f17.cb13e","name":"Run","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":1030,"y":940,"wires":[["cbbd1da2.96db1"]]},{"id":"b9a837d1.29aa38","type":"debug","z":"615b3f17.cb13e","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1690,"y":940,"wires":[]},{"id":"cbbd1da2.96db1","type":"http request","z":"615b3f17.cb13e","name":"","method":"GET","ret":"obj","paytoqs":"ignore","url":"http://10.66.2.183:7125/printer/objects/query?filament_switch_sensor","tls":"","persist":false,"proxy":"","authType":"","x":1350,"y":940,"wires":[["b9a837d1.29aa38"]]}]`

Copy the code above and import it into node-red using the Import menu option, then change the IP

**Comment by jonferreira** [comment]
Thanks.

Klipper noob here and I'm trying to "migrate" my existing node-red + octoprint logic to Octoprint.

Looking for a way to get alerts when a M600 (filament change) is triggered. My understanding was that the gcode_macro object would report when a macro was run rather than allow you to run a macro?

Long story short, what's the easiest way to monitor the gcode being executed so that when Gxxx or Mxxx is executed I can run "something" in node-red?

**Comment by MintyTrebor** [comment]
Sorry - misunderstood the request. (And I am also a klipper noob - I migrated from duet/reprap recently and moonNode is a re-write of my nodeDSF nodes for duet/reprap - so we are both learning....)

I've just added the filament_switch_sensor to the list of objects. It seems to work but just returns an empty object in my config so we will see if it works for you.

Now to the Macro Monitor - The monitoring method described in the docs is not compatible with the method I use in my nodes, however I have figured out a way you can do what you wish.... 

Pre-requisite : In your config have a section `[display_status]` defined.

In your macro add an M117 command at the beginning with an appropriate msg eg `M117 Changing Filament` and another M117 at the end eg `M117 Finished Changing Filament`.
In moonNode monitor node enable the `display status` checkbox (this will be new I've just added it so its not there yet).
In the JSON output display_status.message will update with the text of the M117 message each time a new M117 message is sent.
You can then check for the message "Changing Filament" in node red (with the moonNode Event node or using standard nodes) and trigger whatever action you want....

Does this sound acceptable?

**Comment by jonferreira** [comment]
Hey.

http://10.66.2.183:7125/printer/objects/query?filament_switch_sensor also returns an empty object for me, weird

M117 method is a great idea thanks! The Macro Monitor would be a cool add to your nodes but till then the M117 should work just fine!

Will wait for your commit to test these and report back

**Comment by MintyTrebor** [comment]
You did change the IP address didn't you?

**Comment by jonferreira** [comment]
Yes ofc :)

![image](https://user-images.githubusercontent.com/7714292/129353354-82f51ab4-948b-4b4a-927a-4939b72db469.png)

**Comment by MintyTrebor** [comment]
Had to Check :) I am going to assume you have [filament_switch_sensor ##name##] defined in your config. 
It should work like all the other sensors, but I am unable to verify.

I've Just published 0.0.14 with the changes - it may take a while before the update is recognised in your node-red palette manager.

**Comment by MintyTrebor** [comment]
You can force an update by running
npm install node-red-contrib-moonnode@0.0.14
in your .node-red directory and then restarting node-red
I'm going to close this as an issue, but feel free to update if required.

**Comment by jonferreira** [comment]
Just updated and tested.

display_status works fine, thanks.

filament sensor doesn't seem to do anything. Have it checked, triggered on and off the sensor but no message received

**Comment by jonferreira** [comment]
![image](https://user-images.githubusercontent.com/7714292/129360942-2346c5cf-b22f-4240-b704-33566656156a.png)

**Comment by MintyTrebor** [comment]
I now know why filament sensor was not working - and by finding out why, I am now able to add some better functionality, including gcode_macro (which does not work in the way you think it does from my testing), so my M117 solution is the best way of catching when a macro is run.
I will be pushing another update shortly

**Comment by jonferreira** [comment]
ah cool, great work!

happy to test once it's released

**Comment by MintyTrebor** [comment]
Its because I'm a klipper noob....

**Comment by jonferreira** [comment]
you and me both :D

**Comment by MintyTrebor** [comment]
OK Published

npm install node-red-contrib-moonnode@0.0.15

now you can enter the name of the filament sensor in the node settings

also can do the same for an additional temp sensor and gcode macro
if the macro has a variable defined it will be returned - but it will not get updated when the macro is run - moonraker does not push an update if a variable in a macro is changed...(well it didn't for me but you know - noob here)
![image](https://user-images.githubusercontent.com/26109080/129363210-531765dc-4465-4c8f-831f-939225f6bcbf.png)

**Comment by jonferreira** [comment]
filament_Sensor is working, thanks

![image](https://user-images.githubusercontent.com/7714292/129365692-9ed9775f-b764-4cd6-82f0-1307f0373f6d.png)

gcode_macro, not really but it may be me not knowing how it's supposed to work lol oh well,M117 hack will have to do
