### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by marc-gist** [MintyTrebor/moonNode#5]
Working great so far... a couple things would be appreciated.

1. Status display of monitor node.  Red/Green indicator for when its on/off.
2. Is there a way to slow down the monitor? receiving message every second is quite a lot, or is that just the nature of moonraker?

Thanks for the great work!

**Comment by MintyTrebor** [comment]
1. I'll add it to the "to-do" list.
2. No (or should I say not that I am aware of). Once the connection is established and the subscription setup, MoonRaker controls the frequency of the updates. So if you include objects that change frequently, then you get frequent updates...This is why I added the event node, it allows you to trap the specific values you are interested in and set conditions for the frequency of triggers. There are two types of event parameters Time (how many seconds must elapse before triggering), and delta (how much the value must change by).

**Comment by MintyTrebor** [comment]
FYI: v0.1.01 - Status indicators added to Monitor Node
