### ISSUE TITLE
"TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')" - msg.payload is required 

### ISSUE THREAD

**Issue by QAMC** [MintyTrebor/moonNode#7]
Hello, fantastic work on moonNode, however I would like to know if there is a chance to send the command through moonNode CMD node by just entering the specified command in "Command" field, without the need of msg.payload to exist. 
I often don't sent the msg.payload through my nodes, and when msg.payload is not present the moonNode can't execute the Command. Here is error message:

"TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')"

For me it defeats the purpose of having command in "Command" field if another message in this case msg.payload is still require for it to work. Either I have to create empty msg.payload or entire msg.payload.cmd with wanted command. 
Is there any way of getting out of this issue? 

I'm using Node-RED v2.2.2 and node-red-contrib-moonnode v0.1.2

**Comment by MintyTrebor** [comment]
I can remove the requirement for msg.payload, however a msg object will still be required to trigger the node. I will look to make the change in the next release.

**Comment by QAMC** [comment]
Thanks for reply, if it's really necessary than I understand, but to be honest it would be really nice to have the possibility to properly execute such node without any need of external massages or them to be an objects. My Node red project is getting bigger and bigger and I'm trying to avoid at all cost any unnecessary nodes or massages to avoid later confusion or time spend modifying/debugging stuff.

**Comment by MintyTrebor** [comment]
I am afraid I am not following you - most nodes require an incoming msg to trigger as part of a flow
https://nodered.org/docs/user-guide/messages
unless they are specifically written to start when node red starts...

What are you actually trying to achieve?

**Comment by QAMC** [comment]
Oh I think you're right, basically the goal would be to trigger moonNode CMD with minimal requirements, I think that the lowest I can get is to trigger it with single Inject node without any messages in it. But I can see that it still sends the message as an object, containing _msgid: "6ed8afc14f2665aa". If this is considered as object than I imagine the moonNode CMD triggers properly as you said:
"however a msg object will still be required to trigger the node" 
than I would be very happy, that's all I need to have it working very well.

**Comment by MintyTrebor** [comment]
BY default the injerct node creates the msg.payload with a timestamp value, this is all that is required to trigger the CMD node. I will make the changes as I stated above (it will be better for error trapping as well) in the next release, but in the meantime I am closing this as an issue and treat it as a feature request.

Can I suggest you look into the dashboard nodes - you can create simple interaces with buttons etc, which would allow you to build a nice interface to trigger the commands, it's  really easy to use.

**Comment by QAMC** [comment]
Thank you for understanding and quick respond. I will look forward for the future release. (just from curiosity, when do you plan in to release?)
I am using Dashboard, for many things, one of which is triggering moonNode CMDs to interact with klipper but as I mentioned above, sometimes I'm sending messages not in the payloads, sometimes there are lots of calculations and other nodes, sometimes I need to delete some messages before triggering moonNode CMD, it's just lots of different cases, so having moonNode CMD sending commands by only being triggered by previous nodes would be a pleasure to work with.

**Comment by MintyTrebor** [comment]
FYI : Update published with changes to accept mgs without payload (v 0.1.3)
